fix: attempt 7 to fix CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,20 +47,20 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |          
-          if ${{ steps.check_yarn.outputs.exists == 'true' }} then
+          if ${{ steps.check_yarn.outputs.exists == 'true' }}; then
             echo "manager=yarn" >> $GITHUB_OUTPUT
             echo "command=install" >> $GITHUB_OUTPUT
             echo "runner=yarn" >> $GITHUB_OUTPUT
             exit 0
-          if ${{ steps.check_package.outputs.exists == 'true' }} then
+          fi
+          if ${{ steps.check_package.outputs.exists == 'true' }}; then
             echo "manager=npm" >> $GITHUB_OUTPUT
             echo "command=ci" >> $GITHUB_OUTPUT
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
             exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
           fi
+          echo "Unable to determine package manager"
+          exit 1          
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
